import { z } from 'zod'
import { PaymentMethodSchema } from '@/domain/entities/recurring-item'

export const TransactionSchema = z.object({
	id: z.number(),
	date: z.date(),
	description: z.string(),
	amountGs: z.number().nullable(),
	amountUsd: z.number().nullable(),
	exchangeRateValue: z.number().nullable(),
	exchangeRateId: z.number().nullable(),
	categoryId: z.number(),
	essentialityId: z.number(),
	paymentMethod: PaymentMethodSchema,
	weekOfMonth: z.number().nullable(),
	isInstallment: z.boolean(),
	installmentCurrent: z.number().nullable(),
	installmentTotal: z.number().nullable(),
	installmentPlanId: z.number().nullable(),
	isRecurring: z.boolean(),
	recurringItemId: z.number().nullable(),
	notes: z.string().nullable(),
	createdAt: z.date(),
})
export type Transaction = z.infer<typeof TransactionSchema>

export const CreateTransactionSchema = z.object({
	date: z.coerce.date(),
	description: z.string().min(1),
	categoryId: z.number().int().positive(),
	essentialityId: z.number().int().positive(),
	paymentMethod: PaymentMethodSchema,
	amountGs: z.number().positive().optional(),
	amountUsd: z.number().positive().optional(),
	exchangeRateValue: z.number().positive().optional(),
	exchangeRateId: z.number().int().positive().optional(),
	weekOfMonth: z.number().int().min(1).max(4).optional(),
	isInstallment: z.boolean().optional(),
	installmentCurrent: z.number().int().positive().optional(),
	installmentTotal: z.number().int().positive().optional(),
	installmentPlanId: z.number().int().positive().optional(),
	isRecurring: z.boolean().optional(),
	recurringItemId: z.number().int().positive().optional(),
	notes: z.string().optional(),
})

export const UpdateTransactionSchema = z.object({
	date: z.coerce.date().optional(),
	description: z.string().min(1).optional(),
	amountGs: z.number().positive().nullable().optional(),
	amountUsd: z.number().positive().nullable().optional(),
	exchangeRateValue: z.number().positive().nullable().optional(),
	exchangeRateId: z.number().int().positive().nullable().optional(),
	categoryId: z.number().int().positive().optional(),
	essentialityId: z.number().int().positive().optional(),
	paymentMethod: PaymentMethodSchema.optional(),
	weekOfMonth: z.number().int().min(1).max(4).nullable().optional(),
	isInstallment: z.boolean().optional(),
	installmentCurrent: z.number().int().positive().nullable().optional(),
	installmentTotal: z.number().int().positive().nullable().optional(),
	installmentPlanId: z.number().int().positive().nullable().optional(),
	isRecurring: z.boolean().optional(),
	recurringItemId: z.number().int().positive().nullable().optional(),
	notes: z.string().nullable().optional(),
})
